server:
  port: 8080

#enabled normally true but if set to false can speed up testing if debugging.
ct:
  friendlyName: CryptoTrades-E1
  driver-class-name: com.mysql.jdbc.Driver
  jdbc-url: jdbc:mysql://localhost:3306/crypto_trans
  username: peason
  password: my_crypto
  schema:   crypto_trans
  enabled:  true
  allowedtables:  trades,ledgers,cryptorates,fiatrates,sources,profiles,sources

profileUsername : peason



